### ISSUE TITLE
Polyphonic version of Gravy

### ISSUE THREAD

**Issue by DaveBenham** [cosinekitty/sapphire#74]
It would be wonderful if Gravy fully supported polyphony for all inputs and outputs.

Could the mode switch be replaced with two more pairs of outputs to provide simultaneous availability of LP, BP, and HP? I thought simultaneous availability of different modes is one of the advantages of many hardware SVFs

**Comment by cosinekitty** [comment]
I was thinking along the same lines, and in fact it would probably make sense to provide the same filter logic in purely polyphonic form in a new module. I could call it "polygravy" or "Pea Gravy", LOL. Then there would be no notion of stereo L, R, with the complicated options I currently have for input/output modes. Instead, you get one polyphonic input and one polyphonic output, and all the CV controls would handle polyphonic operation also. I really think it would be easier to create a new module so that I can avoid breaking patches that already exist out there (including my own).

**Comment by cosinekitty** [comment]
Oh yes, and I like the idea of LP, BP, and HP simultaneous outputs, especially because in this new module, they would require only 3 output ports, not L and R for each one.

**Comment by cosinekitty** [comment]
Hi @DaveBenham! I have created a polyphonic version of Gravy called PGravy. (Please don't think about that name too much or it becomes disturbing.) It is in a topic branch [polygravy](https://github.com/cosinekitty/sapphire/tree/polygravy).

Here is a release candidate build for you to play with:
https://github.com/cosinekitty/sapphire/actions/runs/11506571825

This has complete polyphony across the audio input port and all the CV input ports. It provides simultaneous polyphonic outputs for lowpass, bandpass, and highpass. Each has an independent automatic gain limiter, but with a single level control across all 3, in the right-click menu.

Here is a side-by-side panel comparison between Gravy and PGravy:

![image](https://github.com/user-attachments/assets/cb1e873a-e07c-405c-81e9-480564e8e962)

**Comment by cosinekitty** [comment]
I fixed a cosmetic glitch. Now Gravy and PGravy are better matched:

![image](https://github.com/user-attachments/assets/15f91bc3-9e51-4cfe-9734-adcb3c581ec2)

Updated in:
https://github.com/cosinekitty/sapphire/actions/runs/11507168179

**Comment by DaveBenham** [comment]
Now that's what I'm talkin' about!

I haven't tried it yet, but it looks great!

Based on my limited experiments with gravy, I think it will pair great with Benjolin Oscillator.

I think I am interested in using some of that code to create a full blown Oscillator with SVF included. What do you think?

**Comment by DaveBenham** [comment]
Oh - BTW. I am find with PGravy (though I do agree with your warning).

But, what do you think about Sauce or Saucy instead?

**Comment by cosinekitty** [comment]
> I think I am interested in using some of that code to create a full blown Oscillator with SVF included. What do you think?

That sounds really interesting! You are welcome to copy-n-paste my SVF code, or I can help adapt the filter to what you need. It's really simple and efficient. BaconPaul says the Surge XT team uses that SVF filter algorithm all over the place; he is the one who pointed me in that direction for a simple but good filter.

> But, what do you think about Sauce or Saucy instead?

I'm totally open to a name change, because I like simple word names, not acronyms, etc. Since Gravy is a noun, Sauce has a parallel meaning of course, and sounds good too! I will go with Sauce.

**Comment by cosinekitty** [comment]
Renamed PGravy to Sauce in: https://github.com/cosinekitty/sapphire/actions/runs/11510196452

![image](https://github.com/user-attachments/assets/3dc973bc-918d-4be8-aa96-b534f88b8e3e)

**Comment by cosinekitty** [comment]
Sapphire Sauce release candidate is ready in 5e4137554b215d48a16d1e9f10a4439d8b99ac26.
